# Generated by Django 3.2.16 on 2022-12-28 00:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eligibility", "0002_country_import"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "country_of_birth_other",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Only valid if not one of the countries listed above.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "residence_other",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Only valid if not one of the countries listed above.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "country_of_birth",
                    models.ForeignKey(
                        blank=True,
                        help_text="If not one of these countries, leave blank and type below.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="players_born",
                        to="eligibility.country",
                    ),
                ),
                (
                    "residence",
                    models.ForeignKey(
                        blank=True,
                        help_text="If not one of these countries, leave blank and type below.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="players_resident",
                        to="eligibility.country",
                    ),
                ),
            ],
        ),
    ]
