# Generated by Django 3.2.16 on 2022-12-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eligibility", "0004_grandparent_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grandparent",
            options={"verbose_name": "grandparent"},
        ),
        migrations.AddField(
            model_name="grandparent",
            name="adopted",
            field=models.BooleanField(
                default=False,
                help_text="Tick if this parental relationship is not biological.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parent",
            name="adopted",
            field=models.BooleanField(
                default=False,
                help_text="Tick if this parental relationship is not biological.",
            ),
            preserve_default=False,
        ),
    ]
