# Generated by Django 3.2.16 on 2023-01-02 02:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eligibility", "0005_adoption"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerDeclaration",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Automatically recorded time that the declaration was saved.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        editable=False,
                        help_text="Name of the player that made this declaration.",
                        max_length=100,
                    ),
                ),
                (
                    "eligible_for",
                    models.JSONField(
                        editable=False,
                        help_text="List of countries that submitted data indicates the player is eligible to represent.",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        editable=False,
                        help_text="Serialized data that locks the values in time.",
                    ),
                ),
                (
                    "elected_country",
                    models.ForeignKey(
                        help_text="Country that this player has elected to play for, from their available choices.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="available_for_selection",
                        to="eligibility.country",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declarations",
                        to="eligibility.player",
                    ),
                ),
                (
                    "supersceded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eligibility.playerdeclaration",
                    ),
                ),
            ],
        ),
    ]
