# Generated by Django 3.2.16 on 2023-01-21 23:47

from django.db import migrations

import eligibility.fields


class Migration(migrations.Migration):

    dependencies = [
        ("eligibility", "0006_playerdeclaration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parent",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="playerdeclaration",
            options={"ordering": ("-timestamp",)},
        ),
        migrations.AlterField(
            model_name="parent",
            name="adopted",
            field=eligibility.fields.BooleanField(
                help_text="Tick if this parental relationship is not biological."
            ),
        ),
        migrations.AlterField(
            model_name="playerdeclaration",
            name="data",
            field=eligibility.fields.JSONField(
                editable=False,
                help_text="Serialized data that locks the values in time.",
            ),
        ),
    ]
