# Generated by Django 3.2.16 on 2023-02-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eligibility", "0008_auto_20230204_0155"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grandparent",
            name="date_of_birth",
            field=models.DateField(help_text="Please use YYYY-MM-DD format."),
        ),
        migrations.AlterField(
            model_name="parent",
            name="date_of_birth",
            field=models.DateField(help_text="Please use YYYY-MM-DD format."),
        ),
        migrations.AlterField(
            model_name="player",
            name="date_of_birth",
            field=models.DateField(help_text="Please use YYYY-MM-DD format."),
        ),
    ]
