# Generated by Django 3.2.17 on 2023-02-11 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eligibility", "0010_parent_grandparent_unique_name_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerdeclaration",
            name="author",
            field=models.ForeignKey(
                editable=False,
                help_text="The user who made this declaration for the player.",
                null=True,
                on_delete=models.PROTECT,
                related_name="declarations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
