# Generated by Django 3.2.17 on 2023-02-11 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eligibility", "0012_playerdeclaration_author_backfill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerdeclaration",
            name="author",
            field=models.ForeignKey(
                editable=False,
                help_text="The user who made this declaration for the player.",
                on_delete=models.PROTECT,
                related_name="declarations",
                to="auth.user",
            ),
        ),
    ]
