# Generated by Django 3.2.17 on 2023-02-13 12:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eligibility", "0014_playerdeclaration_evidence_nation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("team_date", models.DateField(blank=True, null=True)),
                ("squad_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ("start_date",),
            },
        ),
        migrations.CreateModel(
            name="NationalSquad",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=models.PROTECT,
                        related_name="squads",
                        to="eligibility.event",
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        blank=True, to="eligibility.PlayerDeclaration"
                    ),
                ),
            ],
            options={
                "ordering": ("event", "name"),
                "unique_together": {("event", "name")},
            },
        ),
    ]
