# Generated by Django 3.2.17 on 2023-02-24 22:24

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eligibility", "0016_event_rename_closing_date_and_meta"),
    ]

    operations = [
        migrations.CreateModel(
            name="NationalTeam",
            fields=[
                (
                    "squad",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="eligibility.nationalsquad",
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to=django.db.models.expressions.F(
                            "squad__players"
                        ),
                        to="eligibility.PlayerDeclaration",
                    ),
                ),
            ],
            options={
                "ordering": ("squad",),
                "unique_together": {("squad",)},
            },
        ),
    ]
