# Generated by Django 3.2.17 on 2023-05-07 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eligibility", "0017_nationalteam"),
    ]

    operations = [
        migrations.AddField(
            model_name="grandparent",
            name="exceptions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grandparent",
            name="min_biological_parents",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="parent",
            name="exceptions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parent",
            name="min_biological_parents",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="exceptions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="min_biological_parents",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
