# Generated by Django 3.2.17 on 2023-07-20 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eligibility", "0018_person_exceptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grandparent",
            name="min_biological_parents",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nationalteam",
            name="players",
            field=models.ManyToManyField(
                blank=True, to="eligibility.PlayerDeclaration"
            ),
        ),
        migrations.AlterField(
            model_name="nationalteam",
            name="squad",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                primary_key=True,
                serialize=False,
                to="eligibility.nationalsquad",
            ),
        ),
        migrations.AlterField(
            model_name="parent",
            name="min_biological_parents",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="min_biological_parents",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
