# Generated by Django 3.2.17 on 2023-07-20 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eligibility", "0019_auto_20230720_1048"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerdeclaration",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="playerdeclaration",
            name="verified_comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
