# Generated by Django 3.2.17 on 2023-07-20 21:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eligibility", "0021_alter_playerdeclaration_verified_comments"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclarationExceptionRequest",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Reason for the exception request. Provide explanation for why you are unable to meet the minimum requirements."
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eligibility.player",
                    ),
                ),
            ],
        ),
    ]
